language: cpp
branches:
  only:
  - master
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt install libgtest-dev -y
script:
- mkdir gtest
- cd gtest
- cmake /usr/src/gtest/
- cmake --build .
- sudo cp *.a /usr/lib/
- cd ..
- git clone https://github.com/google/benchmark.git
- git clone https://github.com/google/googletest.git benchmark/googletest
- mkdir build
- cd build
- cmake  -DCMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cmake --build . --target test
- bin/benchmark_allocator
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -v -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvaefremov:$BINTRAY_API_KEY "https://api.bintray.com/content/vaefremov/otus_hw/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
